// TODO: Decide on whether we want img as info sent from backend
const buildingDataJson = {
  "K-F8": { name: "Law", id: "K-F8", img: "" },
  "K-E12": { name: "UNSW Business School", id: "K-E12", img: "" },
  "K-D26": { name: "Biological Sciences North", id: "K-D26", img: "" },
  "K-D23": { name: "Mathews Theatres", id: "K-D23", img: "" },
  "K-E19": { name: "Central Lecture Block", id: "K-E19", img: "" },
  "K-F23": { name: "Mathews Building", id: "K-F23", img: "" },
  "K-B16": { name: "Colombo Building", id: "K-B16", img: "" },
  "K-C24": { name: "Sir John Clancy Auditorium", id: "K-C24", img: "" },
  "K-F20": { name: "John Goodsell Building", id: "K-F20", img: "" },
  "K-G6": { name: "Blockhouse", id: "K-G6", img: "" },
  "K-G19": { name: "John Niland Scientia", id: "K-G19", img: "" },
  "K-E15": { name: "Quadrangle", id: "K-E15", img: "" },
  "K-E4": { name: "Squarehouse", id: "K-E4", img: "" },
  "K-K15": { name: "Old Main Building", id: "K-K15", img: "" },
  "K-H13": { name: "Red Centre", id: "K-H13", img: "" },
  "K-E8": { name: "Science and Engineering", id: "K-E8", img: "" },
  "K-G17": { name: "Electrical Engineering Building", id: "K-G17", img: "" },
  "K-M15": { name: "Rubert Myers Building", id: "K-M15", img: "" },
  "K-F17": { name: "Rex Vowels Theatre", id: "K-F17", img: "" },
  "K-K14": { name: "Physics Theatre", id: "K-K14", img: "" },
  ONLINE: { name: "ONLINE", id: "ONLINE", img: "" },
  "K-K17": { name: "CSE Building", id: "K-K17", img: "" },
  "K-J17": { name: "Ainsworth", id: "K-J17", img: "" },
  "K-J12": { name: "Newton Building", id: "K-J12", img: "" },
  "K-G14": { name: "Webster Building", id: "K-G14", img: "" },
  "K-G15": { name: "Webster Theatres", id: "K-G15", img: "" },
  "K-G27": { name: "AGSM", id: "K-G27", img: "" },
  "K-H6": { name: "Tyree", id: "K-H6", img: "" },
  "K-C20": { name: "Morven Brown Building", id: "K-C20", img: "" },
  "K-J18": { name: "Willis Annexe", id: "K-J18", img: "" },
  "K-F10": { name: "Chemical Sciences", id: "K-F10", img: "" },
  "K-D16": { name: "Goldstein Hall", id: "K-D16", img: "" },
  "K-H20": { name: "Civil Engineering Building", id: "K-H20", img: "" },
  "K-H22": { name: "Vallentine Annexe", id: "K-H22", img: "" },
  "K-E26": { name: "Biological Sciences South", id: "K-E26", img: "" },
  "K-J14": { name: "Keith Burrows Theatre", id: "K-J14", img: "" },
  "K-F13": { name: "Science Theatre", id: "K-F13", img: "" },
  "P-F": { name: "P-F", id: "P-F", img: "" },
  "P-D": { name: "P-D", id: "P-D", img: "" },
  "P-E": { name: "P-E", id: "P-E", img: "" },
};

export default buildingDataJson;
