"use strict";
exports.__esModule = true;
var axios_1 = require("axios");
var LIBRARY_BOOKINGS_URL = "https://unswlibrary-bookings.libcal.com/";
var location = 6581;
var zone = 0;
var category = 0;
var capacity = 0;
var url = "https://unswlibrary-bookings.libcal.com/r/new/availability?lid=".concat(location, "&zone=").concat(zone, "&gid=").concat(category, "&capacity=").concat(capacity);
var response = axios_1["default"].get(url);
console.log(response);
